document.writeln("<object id=\"mtv516Player\" width=336 height=65");
document.writeln(" classid=\"CLSID:6BF52A52-394A-11D3-B153-00C04F79FAA6\" type=application\/x-oleobject standby=\"Loading Windows Media Player ");
document.writeln("");
document.writeln("components...\">");
document.writeln("             <param name=\"URL\" value='"+url+"'>");
document.writeln("              <param name=\"Album\" value=\"在线广播台\"\/>");
document.writeln("              <param name=\"rate\" value=\"1\">");
document.writeln("              <param name=\"balance\" value=\"0\">");
document.writeln("              <param name=\"currentPosition\" value=\"0\">");
document.writeln("              <param name=\"defaultFrame\" value=\"\">");
document.writeln("              <param name=\"playCount\" value=\"100\">");
document.writeln("              <param name=\"autoStart\" value=\"-1\">");
document.writeln("              <param name=\"currentMarker\" value=\"0\">");
document.writeln("              <param name=\"invokeURLs\" value=\"-1\">");
document.writeln("              <param name=\"baseURL\" value=\"\">");
document.writeln("              <param name=\"volume\" value=\"100\">");
document.writeln("              <param name=\"mute\" value=\"0\">");
document.writeln("              <param name=\"uiMode\" value=\"full\">");
document.writeln("              <param name=\"stretchToFit\" value=\"0\">");
document.writeln("              <param name=\"windowlessVideo\" value=\"0\">");
document.writeln("              <param name=\"enabled\" value=\"-1\">");
document.writeln("              <param name=\"enableContextMenu\" value=\"0\">");
document.writeln("              <param name=\"fullScreen\" value=\"0\">");
document.writeln("              <param name=\"SAMIStyle\" value=\"\">");
document.writeln("              <param name=\"SAMILang\" value=\"\">");
document.writeln("              <param name=\"SAMIFilename\" value=\"\">");
document.writeln("              <param name=\"captioningID\" value=\"\">");
document.writeln("              <param name=\"BufferingTime\" value=\"5\">");
document.writeln('              <embed type="audio/x-oleobject" flename="mp" style="width: 336px; height: 65px" codebase="http://activex.microsoft.com/activex/controls/mplayer/en/nsmp2inf.cab#Version=5,1,52,701" playcount="100" src="' + url + '" enablecontextmenu="0"></embed>');
document.writeln("    <\/object>");