document.writeln("<object ID=Realplayer WIDTH=336 HEIGHT=65 CLASSID=CLSID:CFCDAA03-8BE4-11CF-B84B-0020AFBBCCFA>");
document.writeln("<param name=_ExtentX value=9657>");
document.writeln("<param name=_ExtentY value=847>");
document.writeln("<param name=AUTOSTART value=-1>");
document.writeln("<param name=SHUFFLE value=0>");
document.writeln("<param name=PREFETCH value=0>");
document.writeln("<param name=NOLABELS value=0>");
document.writeln("<param name=SRC value='"+url+"'>");
document.writeln("<param name=CONTROLS value=StatusBar,controlpanel>");
document.writeln("<param name=CONSOLE value=Clip1>");
document.writeln("<param name=LOOP value=0>");
document.writeln("<param name=NUMLOOP value=0>");
document.writeln("<param name=CENTER value=0>");
document.writeln("<param name=MAINTAINASPECT value=0>");
document.writeln("<param name=BACKGROUNDCOLOR value=#000000>");
document.writeln("</object>");